spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      # URI moderna (recomendado)
      # Fallback local quando Config Server não estiver disponível
      uri: mongodb://root:password@localhost:27017/product-db?authSource=admin

server:
  port: 8081
