spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      # prefer single URI to avoid deprecated host/port properties
      uri: mongodb://root:password@localhost:27017/product-db?authSource=admin

server:
  port: 8081
