spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        # Use local filesystem 'native' backend during development.
        native:
          # relative to config-server module; file:../config-data points to repo root/config-data
          search-locations: file:../config-data

server:
  port: 8088